### ISSUE TITLE
Problemas con la plataforma android

### ISSUE THREAD

**Issue by Vannesandoval** [alejo8591/unipiloto-am-3#10]
Hola profe, tengo un problema con la plataforma android, no se si sea problema de configuracion. Adjunto pantallazo con el error

Muchas gracias.

![sin titulo](https://cloud.githubusercontent.com/assets/14851812/10913339/77178be8-821b-11e5-8d1f-0072311c9783.png)

**Comment by alejo8591** [comment]
@Vannesandoval por favor prueba instalando: `npm install q -g`

**Comment by Vannesandoval** [comment]
No profe sigue apareciendo lo mismo, no se si tenga que ver con las variables de entorno

**Comment by alejo8591** [comment]
@Vannesandoval por favor muestrame como te quedaron las variables de entorno, copia toda la linea...

**Comment by Vannesandoval** [comment]
ANT_HOME: C:\apache-ant-1.9.6\
JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0_79\
Path: C:\Program Files\Java\jdk1.7.0_79;%C_EM64T_REDIST11%bin\Intel64;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Microchip\MPLAB C32 Suite\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;%PROGRAMFILES%\Internet Explorer;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\Roxio Shared\13.0\DLLShared\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\13.0\DLLShared\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\apache-ant-1.9.6\bin;C:\Program Files (x86)\Java\jdk1.7.0_79\bin

**Comment by alejo8591** [comment]
Teniendo en cuenta la ruta donde tienes el `SDK Manager` por favor agrega a las variables de entorno el Android: `;C:\Development\android-sdk\platform-tools;C:\Development\android-sdk\tools`

**Comment by Vannesandoval** [comment]
Profe las variables de entorno quedarian asi??

ANT_HOME: C:\apache-ant-1.9.6\
JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0_79\
Path: C:\Program Files\Java\jdk1.7.0_79;%C_EM64T_REDIST11%bin\Intel64;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Microchip\MPLAB C32 Suite\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;%PROGRAMFILES%\Internet Explorer;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Common Files\Roxio Shared\13.0\DLLShared\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\13.0\DLLShared\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\apache-ant-1.9.6\bin;C:\Program Files (x86)\Java\jdk1.7.0_79\bin;C:\Users\Vannessa\AppData\Local\Android\android-sdk\platform-tools;C:\Users\Vannessa\AppData\Local\Android\android-sdk\tools

**Comment by alejo8591** [comment]
@Vannesandoval Sí señora tal cual, me cuentas como te va...

**Comment by Vannesandoval** [comment]
No señor.... no quiere funcionar...

**Comment by alejo8591** [comment]
De nuevo imagen del error...

**Comment by Vannesandoval** [comment]
Si señor, el mismo

**Comment by alejo8591** [comment]
@Vannesandoval cuando `AVDs` tienes creados?, tienes el API 22 descargada... hablo del SDK Manager por favor una imagen de los `AVDs`

**Comment by Vannesandoval** [comment]
Espero sea lo que necesitaba ver profe

![sdk](https://cloud.githubusercontent.com/assets/14851812/10929553/e8b3cb92-8282-11e5-97b7-436bd0435756.png)

**Comment by alejo8591** [comment]
@Vannesandoval correcto pero por favor descarga la adecuada para el `build` que es la `API 22`

**Comment by alejo8591** [comment]
@Vannesandoval también te falta que en las variables de entorno dejes lo siguiente: `;%JAVA_HOME%\bin;` y `;%ANT_HOME%\bin;`, entiendo que ya están pero reemplazarlas y dejarlas como te lo indico

**Comment by Vannesandoval** [comment]
Profe lo de la API 22 se refiere a la parte de los AVD's???.... por que en el SDK si estan instalados

**Comment by alejo8591** [comment]
@Vannesandoval es necesario que descargues esta API, ya la descargaste?

**Comment by Vannesandoval** [comment]
si señor, ya lo descargue

**Comment by Vannesandoval** [comment]
Buenas noches profesor

Ya se soluciono el error del "build", pero ahora al momento de emular, aparece el siguiente error. Trate de probarlo por genymotion y tampoco lo hace.

![emulate](https://cloud.githubusercontent.com/assets/14851812/11051168/ddbb3b02-871a-11e5-8ed6-6cbd8b14b936.png)

**Comment by alejo8591** [comment]
@Vannesandoval cuéntame cual fue la solución y segundo que AVDs tienes creadas?

**Comment by Vannesandoval** [comment]
Me toco cambiar la configuración del control de cuentas, para que no molestara por permisos de administrador. Adjunto una imagen con los AVDs creados. En cuanto a genymotion ya me funciono.

Gracais profe

![avd](https://cloud.githubusercontent.com/assets/14851812/11051565/4d836a4c-871e-11e5-85f0-a39340f9fefd.png)

**Comment by alejo8591** [comment]
@Vannesandoval Que bueno :+1: ya puedo espero te haya servido la ayuda!!!

**Comment by Vannesandoval** [comment]
Profe aun tengo el error al momento de emular, solo tengo un AVD creado, pero nose si la configuración este bien. la imagen es la del anterior mensaje

**Comment by alejo8591** [comment]
Tienes instalada arquitectura Intel y/o ARM? revisa que este instalados para la arquitectura que seleccionaste...!!!

**Comment by Vannesandoval** [comment]
Hola profe, si, tengo las dos arquitecturas

**Comment by alejo8591** [comment]
@Vannesandoval Cómo vamos con este problema se pudo solucionar?

**Comment by Vannesandoval** [comment]
No nada profe, cuando hago pruebas lo hago por genymotion o por el celular pero el emulador aun no funciona
