### ISSUE TITLE
Error Genymotion

### ISSUE THREAD

**Issue by jhonariza03** [alejo8591/unipiloto-am-3#11]
Buenas noches profe.

tengo un inconveniente en Genymotion al darle play al virtual devices que instale, me sale el error que  adjunto en la imagen.

me podría indicar que configuración debo hacer en el virtual box para solucionar el inconveniente.

gracias

![error genymotion](https://github-cloud.s3.amazonaws.com/assets%2F14851809%2F10957208%2F263ab928-8330-11e5-89f7-dcdfc559659e.PNG)

**Comment by alejo8591** [comment]
Ya tienes instalado `virtualbox`?, sí es así me muestras que maquinas tienes e intenta abrirla desde allí...

**Comment by jhonariza03** [comment]
profe.. descargué el genymotion que viene con el virtual box, pero no se si toque hacerle algo al virtual box, como crear una maquina virtual o no es necesario?

**Comment by alejo8591** [comment]
Instalar la versión (API) de la maquina virtual correspondiente. Prueba con esto y me cuentas...

**Comment by alejo8591** [comment]
@jhonariza03 Cómo vamos con este error? se pudo solucionar?

**Comment by alejo8591** [comment]
Se da cierre a este caso ya que no hubo respuesta de dudas o preguntas desde hace 13 días
