### ISSUE TITLE
EJERCICIOS DE AJS

### ISSUE THREAD

**Issue by Hlopez1967** [alejo8591/unipiloto-am-3#12]
Cordial saludo profe

Estoy realizando los ejercicios de la guia y hay un ejercicio que no fucniona y no encuentro la falla, a ver si me ayuda profe mil gracias

Trate de pegarlo pero me dice que requiero permiso para este repositorio

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Prueba Angular JS</title>

```
<script src="angular.min.js"></script>
```

</head>

<body>
    <form>

```
    <div ng-app ="acumuladorApp" ng-controller="acumuladorAppCtrl">
        <h1>acumulador</h1>
        <h2>Control de operacion:</h2>
        cuanto? <input type="text" ng-model="vm.cuanto" size="4" />
        <br />

        <input type="button" value="+" ng-click="sumar()" />
        <input type="button" value="-" ng-click="restar()" />
        <h2>totales</h2>
        En el acumulador llevamos <span>{{total}}</span>

        <script type="text/javascript">


            var acumuladorApp = angular.module('acumuladorApp', []);

            acumuladorApp.controller("acumuladorAppCtrl",["$scope", function($scope){

                scope.total = 0;
                scope.cuanto = 0;

                scope.sumar = function(){

                    scope.total += parseInt(scope.cuanto);
                }

                scope.restar = function(){

                    scope.total -= parseint(scope.cuanto)
                }
            }]);

        </script>
    </div>
</form>
```

</body>
</html>

**Comment by alejo8591** [comment]
@Hlopez1967 la siguiente información por favor:
- Número y sección del ejercicio?
- Qué error te sale en la consola de JS del navegador?
- Imagen con la estructura de tus archivos para tener una mejor idea...

**Comment by Hlopez1967** [comment]
profe es una unica pagina html como la que le copie, es el ejercicio 3.4.3 del manual de angular js

**Comment by alejo8591** [comment]
@Hlopez1967 listo:
1. En el controlador `acumuladorAppCtrl` cuando utilizas `$scope` lo haces como `scope`
2. En el input `<input type="text" ng-model="vm.cuanto" size="4" />` utilizas un modelo y objeto JS que se llama `vm` el cual dentro tiene un elemento llamado `cuanto`; cuando en el controlador hace el llamado de este modelo lo haces `scope.cuanto` debería ser `$scope.cuanto` o `$scope.vm.cuanto`

**Comment by davith01** [comment]
Adicional, la función <strong>parseint</strong> de la función <code>$scope.restar</code>, debe ir con 'I' mayúscula <code>parseInt()</code>
Envío el código modificado.

```
<!doctype html>
<html lang="es">
    <head>
        <title>Ejercicio 3.4.3 del manual de angular js </title>
        <script src="angular.js"></script>
    </head>
    <body>
<form>
        <div ng-app ="acumuladorApp" ng-controller="acumuladorAppCtrl">
        <h1>acumulador</h1>
        <h2>Control de operacion:</h2>
        cuanto? <input type="text" ng-model="cuanto" size="4" />
        <br />

        <input type="button" value="+" ng-click="sumar()" />
        <input type="button" value="-" ng-click="restar()" />
        <h2>totales</h2>
        En el acumulador llevamos <span>{{total}}</span>

        <script type="text/javascript">

            var acumuladorApp = angular.module('acumuladorApp', []);
            acumuladorApp.controller("acumuladorAppCtrl",["$scope", function($scope){

                $scope.total = 0;
                $scope.cuanto = 0;

                $scope.sumar = function(){

                    $scope.total += parseInt($scope.cuanto);
                }

                $scope.restar = function(){

                    $scope.total -= parseInt($scope.cuanto);
                }
            }]);

        </script>

    </div>
</form>

</body>
</html>
```

**Comment by alejo8591** [comment]
@davith01 gracias por la colaboración :ok: @Hlopez1967 Cómo nos fue? funciono!!!

**Comment by alejo8591** [comment]
Le doy cierre a este caso ya que se soluciono
