### ISSUE TITLE
Error en wamp

### ISSUE THREAD

**Issue by claudiafranco2709** [alejo8591/unipiloto-am-3#13]
Buenos dias  tengo  una inquietud cuando escribo en el navegador localhost  me sale el siguiente error

Not Found

HTTP Error 404. The requested resource is not found

gracias

**Comment by alejo8591** [comment]
@claudiafranco2709 por favor indicar más información, imagenes, distribución de archivos, sistema operativo, con eso nos damos una mejor idea para ayudarte :smile:

**Comment by alejo8591** [comment]
Qué sucedió con este problema, lo pudiste solventar?

**Comment by claudiafranco2709** [comment]
Buenas noches Profesor  no sigue saliendo el error 

Claudia Franco Mora
Ingeniería de SistemasDepartamento para la Prosperidad Social Grupo Paz Desarrollo y Estabilización

Dirección de Programas Especiales

Calle 16 No. 6-66 piso 12 Edificio Avianca

Tel 5937050 Ext. 7732

Date: Mon, 23 Nov 2015 16:36:15 -0800

**Comment by alejo8591** [comment]
Por favor dame más información; imagenes, estructura de archivos y todo lo que me de más idea del problema...
