### ISSUE TITLE
Error comando adb devices

### ISSUE THREAD

**Issue by fromopac86** [alejo8591/unipiloto-am-3#14]
Buenos días,   no he podido emular en Genymotion,   al aplicar el adb devices me aparece "adb" no se reconoce como comando interno o externo. 
El path está de la siguiente forma, no se si estoy cometiendo algún error u omitiendo algo:
C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;C:\Users\pacho\AppData\Roaming\npm;C:\Users\pacho\AppData\Local\Android\android-sdk;%JAVA_HOME%\bin;%ANT_HOME%\bin

![1](https://cloud.githubusercontent.com/assets/14851834/11215284/6c0308d8-8d13-11e5-9384-9498c222f33c.jpg)

**Comment by alejo8591** [comment]
Tienes que especificar en el `path` general, las rutas de `platform-tools` y `tools` eso esta en la guía... por favor revisar y me cuentas

**Comment by alejo8591** [comment]
@fromopac86 cómo te fue con las ultimas indicaciones que te escribí?

**Comment by fromopac** [comment]
Bien!!!

**Comment by alejo8591** [comment]
Perfecto entonces doy cierre al issue  ;)
