### ISSUE TITLE
Problemas IONIC

### ISSUE THREAD

**Issue by Vannesandoval** [alejo8591/unipiloto-am-3#15]
hola profe, estuve ensayando el ejemplo de clase (realizado por Ionic Creator) y sigo con el mismo problema, me muestra un proyecto en blanco

**Comment by alejo8591** [comment]
Indícame como lo estas haciendo, desde que lo creas hasta cuando lo ejecutas

**Comment by Vannesandoval** [comment]
Una vez creo el proyecto en ionic creator le digo exportar, en la consola dentro de la carpeta del modulo, primero ingreso a la cuenta, despues copio la instruccion que me arroja ionic creator con el nombre que le di al proyecto, entro a la carpeta del proyecto y le doy la instrucción "ionic serve"

**Comment by alejo8591** [comment]
Pero cómo exportas el proyecto y cómo lo sincronizas localmente? Que comando y cómo lo llamas, dime el ejemplo de comando

**Comment by Vannesandoval** [comment]
Comando desde ionic creator

ionic start lab6 creator:92b840076e71

![ionic](https://cloud.githubusercontent.com/assets/14851812/11388784/cbb846a4-9307-11e5-8f69-b8fc00e1dde4.png)

**Comment by alejo8591** [comment]
Borra todas las apps que tienes en el dashboard y muestrame la App que vas a exportar cuando lo estés haciendo haber cómo queda en la web, adicionalmente borra todos los cookies y el historial

**Comment by alejo8591** [comment]
En la carpeta general de tu usuario en windows o en mis documentos, busca una carpeta, que puede estar oculta, llamada `.ionic`, la eliminas y en la linea de comandos vuelves a ingresar a `ionic login` y de nuevo exporta tu proyecto de `IONIC Creator`.
