### ISSUE TITLE
error lab9 ejemplos cordova

### ISSUE THREAD

**Issue by fromopac86** [alejo8591/unipiloto-am-3#17]
Profe me aparece un error al darle guardar en el formulario del lab9.

![image](https://cloud.githubusercontent.com/assets/14851834/11431314/7be8cba0-9463-11e5-9e27-86ec7d450049.png)

![image](https://cloud.githubusercontent.com/assets/14851834/11431319/a0c47b7c-9463-11e5-8c51-7e0c29b1a286.png)

**Comment by alejo8591** [comment]
@fromopac86 es el mismo error que nos esta apareciendo cuando utilizamos `ngCordova` dejame y reviso como lo publicamos directamente en el repositorio del plugin
