### ISSUE TITLE
Problema Instalación Node,js

### ISSUE THREAD

**Issue by Vannesandoval** [alejo8591/unipiloto-am-3#4]
Buenas noches profe, voy a instalar el Node.js, lo descargo de la pagina web y al ejecutarlo me aparece el mensaje de la imagen, que puedo hacer para poder instalarlo.

Gracias

**Comment by alejo8591** [comment]
@Vannesandoval por favor adjunta la imagen para poder ayudarte...

**Comment by Vannesandoval** [comment]
![problema nodejs](https://cloud.githubusercontent.com/assets/14851812/10736391/b3287f3a-7bda-11e5-84e0-3eef06971c1a.png)

**Comment by alejo8591** [comment]
@Vannesandoval cuéntame cual estas descargando el `.exe` o el `.msi`, que arquitectura tienes?, y si antes ya lo habías instalado?

**Comment by Vannesandoval** [comment]
Buenas tardes profe... la versión es esta: "node-v4.2.1-x64" y hasta ahora lo estoy instalando

**Comment by alejo8591** [comment]
Por favor prueba instalando esta versión: https://nodejs.org/dist/v4.2.1/win-x64/node.exe en caso tal de que falle prueba con esta otra: https://nodejs.org/dist/v4.2.1/node-v4.2.1-x64.msi

**Comment by alejo8591** [comment]
Sí te fallan estas dos opciones intenta con lo siguiente; borrar el contenido de `C:\Users\x\AppData\Local\Temp` y cuando vas a instalar, con clic derecho, indicar los privilegios de administrador...

**Comment by Vannesandoval** [comment]
Probe con esta versión: https://nodejs.org/dist/v4.2.1/win-x64/node.exe y me aparece lo que se observa en la imagen, tiene que aparecer algo mas o escribir algo?

Sin embargo borre lo de la carpeta Temporal, pero aun no me deja instalar la primera opción

![node](https://cloud.githubusercontent.com/assets/14851812/10738202/3347a9f8-7be4-11e5-985e-e8b15cc1fe8a.png)

gracias,

**Comment by alejo8591** [comment]
@Vannesandoval con esta instalación te aparece el `Node.js Command prompt`?

**Comment by Vannesandoval** [comment]
Profe con respecto a este error, copie el instalador al disco C y abri el cmd y le di el comando msiexec.exe -i C:\nombre-archivo.msi

**Comment by alejo8591** [comment]
@Vannesandoval perfecto y muchas gracias por la información
