### ISSUE TITLE
Problema ejercicio

### ISSUE THREAD

**Issue by Vannesandoval** [alejo8591/unipiloto-am-3#6]
var gulp = require('gulp'),
    cssmin = require('gulp-cssmin'),
    rename = require('gulp-rename'),
    concatCss = require('gulp-concat-css'),
    concat = require('gulp-concat'),
    uglify = require('gulp-uglify');

gulp.task('minify-files', function(){
    return gulp.src(['css/styles.css'])
        .pipe(concatCss('bundle.css'))
        .pipe(uglify())
        .pipe(gulp.dest('build/'));
});

gulp.task('concat-files', function(){
    return gulp.src(['assets/jquery-1.11.2.min.js', 'js/lab3.js'])
        .pipe(concat('lab3.min.js'))
        .pipe(gulp.dest('build/js/'));
});

gulp.task('concat-files', ['minify-files'], function(){ 
  return gulp.src('build/bundle.css')
    .pipe(cssmin())
    .pipe(rename({suffix: 'styles.min'}))
    .pipe(gulp.dest('build/dist/'));
});

/_El que se debe ejecutar es la ultima tarea, en este caso minify depende de concat_/

**Comment by alejo8591** [comment]
Revisa entre lineas; en formato de comentario las cosas a revisar y/o corregir

``` javascript

var gulp = require('gulp'),
cssmin = require('gulp-cssmin'),
rename = require('gulp-rename'),
concatCss = require('gulp-concat-css'),
concat = require('gulp-concat'),
uglify = require('gulp-uglify');

gulp.task('minify-files', function(){
return gulp.src(['css/styles.css'])
.pipe(concatCss('bundle.css'))
/* 
 * gulp-uglify === uglify
 * Este modulo funciona bien para JS para CSS en gulp-cssmin
*/
.pipe(uglify())
.pipe(gulp.dest('build/'));
});

gulp.task('concat-files', function(){
return gulp.src(['assets/jquery-1.11.2.min.js', 'js/lab3.js'])
.pipe(concat('lab3.min.js'))
.pipe(gulp.dest('build/js/'));
});

gulp.task('concat-files', ['minify-files'], function(){ 
return gulp.src('build/bundle.css')
.pipe(cssmin())
.pipe(rename({suffix: 'styles.min'}))
.pipe(gulp.dest('build/dist/'));
});

```
