### ISSUE TITLE
gulpfile.js

### ISSUE THREAD

**Issue by camiloz9** [alejo8591/unipiloto-am-3#7]
var gulp = require('gulp'),
    cssmin = require('gulp-cssmin'),
    rename = require('gulp-rename'),
    concatCss = require('gulp-concat-css');

gulp.task('concat-css', function(){
    return gulp.src('css/*.css')
        .pipe(concatCss('bundle.css'))
        .pipe(gulp.dest('css/'));
});

gulp.task('minify-css', ['concat-css'], function(){
  return gulp.src('css/bundle.css')
    .pipe(cssmin())
    .pipe(rename({suffix: '.min'}))
    .pipe(gulp.dest('dist/'));
});

**Comment by alejo8591** [comment]
Ya lo estuve probando y no tuve problema alguno, en clase volvemos a revisar haber que ocurre :smile:

**Comment by alejo8591** [comment]
Se da cierre a este caso, pues funciona correctamente ;)
