### ISSUE TITLE
Problema Simuladores FIREFOX OS

### ISSUE THREAD

**Issue by pablo1104** [alejo8591/unipiloto-am-3#8]
Buenos dìas.

Reporto el siguiente problema. Luego de abrir los simuladores de Firefox OS, en las versiones 1.3, 1.4 y 2.0, a los pocos segundos se cierra el simulador y muestra el error que se visualiza en la imagen.

![error_sim_firefox_os](https://cloud.githubusercontent.com/assets/14851797/10864150/8a7168d2-7fb2-11e5-8678-7f1b8001e1da.png)

**Comment by alejo8591** [comment]
@pablo1104 por favor probar con lo siguiente:
1. Desinstalar el Firefox  por completo.
3. Instalar Firefox Developer Edition en su versión más estable.
4. Descargar los respectivos plugin como `ADB-Helper` y una versión del sistema operativo `Firefox OS`

**Comment by alejo8591** [comment]
Cómo nos fue con este problema se pudo solucionar?
